export default {
    preset: "ts-jest",
    testEnvironment: "jsdom",
    moduleFileExtensions: ["ts", "tsx", "js", "jsx"],
    transform: {
        "^.+\\.(ts|tsx)$": [
            "ts-jest",
            {
                tsconfig: {
                    jsx: "react-jsx",
                    esModuleInterop: true,
                },
            },
        ],
    },
    testMatch: ["**/__tests__/**/*.(ts|tsx)", "**/*.(test|spec).(ts|tsx)"],
    collectCoverageFrom: [
        "src/**/*.(ts|tsx)",
        "!src/**/*.d.ts",
        "!src/main.tsx",
        "!src/vite-env.d.ts",
        "!src/App.tsx",
        "!src/components/navbar/BreadCrumb.tsx",
        "!src/components/dashboard/ChartPieDonut.tsx",
        "!src/components/dashboard/chartMapPoint/**/*",
        "!src/components/dashboard/chartTableData/**/*",
        "!src/components/rightbar/Activities.tsx",
        "!src/components/rightbar/Contacts.tsx",
        "!src/components/sidebar/Sidebar.tsx",
        "!src/components/sidebar/MenuItem.tsx",
        "!src/components/orderlist/OrderListTable.tsx",
        "!src/pages/**/*",
        "!src/components/ui/chart.tsx",
        "!src/components/ui/checkbox.tsx",
        "!src/components/ui/command.tsx",
        "!src/components/ui/dialog.tsx",
        "!src/components/ui/dropdown-menu.tsx",
        "!src/components/ui/pagination.tsx",
        "!src/components/ui/separator.tsx",
        "!src/components/ui/sheet.tsx",
        "!src/components/ui/sidebar.tsx",
        "!src/components/ui/skeleton.tsx",
        "!src/components/ui/tooltip.tsx",
    ],
    setupFilesAfterEnv: ["<rootDir>/src/setupTests.ts"],
    moduleNameMapper: {
        "\\.(css|less|scss|sass)$": "identity-obj-proxy",
        "\\.(png|jpg|jpeg|gif|svg)$": "jest-transform-stub",
        "^@/(.*)$": "<rootDir>/src/$1",
    },
    globals: {
        TextEncoder: TextEncoder,
        TextDecoder: TextDecoder,
    },
};
